display:
  width: 800
  height: 600
  update_frequency: 60

drone:
  thrust: 40 # Newtons
  mass: 0.1 # Kilograms
  inertia: 2 # Kilogram meters squared
  gravity: 2
  motors:
    - [-0.5, 0, -90] # X offset from drone center, Y offset from drone center, rotation relative to drone center
    - [0.5, 0, -90]
