display:
  width: 800
  height: 600
  update_frequency: 60

environment:
  gravity: 3

drone:
  thrust: 10 # Newtons
  mass: 0.1 # Kilograms
  inertia: 25 # Kilogram meters squared
  motors:
    - [-50, 0, 90] # X offset from drone center, Y offset from drone center, rotation relative to drone center
    - [50, 0, 90]
